### ISSUE TITLE
Cannot import .bck files into Blender? (animation files)

### ISSUE THREAD

**Issue by NoobisTF** [niacdoial/blemd#9] opened 2017-12-04 22:04 UTC
I am most likely doing something wrong, but I cannot seem to import the .bck files into Blender. I installed the plugin correctly, but when I go to Import and Nintendo BMD, the .bck files are not visible. I can import the .bmd files fine, though. Help? Thanks!

**Comment by niacdoial** [comment] 2017-12-09 12:39
Hello!
Sorry for answering this late, but .BCK files only contain animations.
To import them, you need a model to apply them on (ideally the associated
one).

If the "import animations" option is checked, while importing a .BMD file,
blemd will look for animations that can apply to it (aka has the same
number of animation bones).

Those animations (.BCK files) will be detected if they are in the "../bck/"
(or similar) directory relatively to the .BMD file.

Also note that a large number of animation files in the same folder can
slow the script so much that blender might freeze while importing.

I hope that was clear enough.
Have a nice day!

**Comment by NoobisTF** [comment] 2017-12-09 16:37
Yeah, I have that checked.

The thing is, some of the animations will import on some models. But some won't.
The one I'm trying to get to work is the Armogohma model, but the animaions don't import, and I get this error on BMD Import:

[https://imgur.com/a/AWnr5](url)

The mesh, by the way, imports fine. 
Thanks!

**Comment by niacdoial** [comment] 2017-12-09 17:44
Er.....
Does this error only happen when importing animations?
(if so, I have no idea of how it happened)
Can I have the model that caused this bug, please?

Also, it seems (according to what I tested anyways) that it is normal to
have, in the same folder, ".bck" files for different models.
Only the animations that seem to match the model will be imported (and will
play one after the other).
have a nice day!


2017-12-09 17:37 GMT+01:00 NoobisTF <notifications@github.com>:

**Comment by NoobisTF** [comment] 2017-12-09 17:56
Yeah, sure, here it is:

The .arc file:
https://www.dropbox.com/s/fj85u4d1vhkovvt/B_gm.arc?dl=0

The folders after decompile:
https://www.dropbox.com/s/yjwky1zzva10gi5/files.rar?dl=0

Thanks!

**Comment by NoobisTF** [comment] 2017-12-17 18:07
Were you able to take a look?

**Comment by niacdoial** [comment] 2017-12-17 19:11
The version on my computer works. I'll have to make other tests to make
sure I didn't break anything else by making one of my "recent" updates.
however, I am often busy and/or without internet. I hope everything will be
online in a week (because holidays).
thanks for your patience.

2017-12-17 19:07 GMT+01:00 NoobisTF <notifications@github.com>:

**Comment by NoobisTF** [comment] 2017-12-17 19:24
Well okay

**Comment by niacdoial** [comment] 2017-12-23 20:39
Here it is!
Everything I have ever tested my addon on now is successfully imported.

**Comment by NoobisTF** [comment] 2017-12-23 20:42
Hm.. is there something I could have done wrong, then?

**Comment by niacdoial** [comment] 2017-12-23 20:46
er.... By "here it is", I meant "new commit", with the bug fixed. Like 1 min beforehand.
Sorry if I was unclear in my previous message.

**Comment by NoobisTF** [comment] 2017-12-23 20:47
Ohhh my mistake. Sorry!

**Comment by NoobisTF** [comment] 2017-12-23 20:53
Sorry to bug you more.. but it reads this error when I try to import a bmd:
https://i.imgur.com/KFWMRGI.jpg

**Comment by niacdoial** [comment] 2017-12-23 20:57
Er......
It sounds similar to a stupid bug I had a while ago.
Does it still crash if you try a second time?

**Comment by niacdoial** [comment] 2017-12-23 20:58
If so ,could you send me a screenshot of the console within blender (window-> toggle system console), please?

**Comment by NoobisTF** [comment] 2017-12-23 20:58
Hm no, it just prints the same error everytime

**Comment by niacdoial** [comment] 2017-12-23 21:01
Is it a not-windows machine? I just realised that my ~~stupid~~ code calls an .exe file, and passes errors silently if said call fails

**Comment by NoobisTF** [comment] 2017-12-23 21:02
Nope, mine is indeed Windows.

**Comment by niacdoial** [comment] 2017-12-23 21:15
welp.
*starts IDE*
In the meantime, I suggest you open the bmd file in bmdview2 (there shoud be a link in the readme), and  use the "save textures" option once it is done, to put all the texture files into the "name\Textures" folder next to "name.bmd", using the naming convention seen in the last line of the error you saw.
Or maybe it would be easier to browse the old versions of this addon and find one that exports images properly(https://github.com/niacdoial/blemd/commit/68045495ad00bbfd60092649c9e092cf35ba9738 probably)

**Comment by NoobisTF** [comment] 2017-12-23 21:22
Oh, so the problem are the textures?

**Comment by niacdoial** [comment] 2017-12-23 21:30
yup. they aren't properly exported, somehow.  (the image files aren't even written...)

**Comment by NoobisTF** [comment] 2017-12-23 21:44
Alright, so is it something I could be doing wrong?

**Comment by niacdoial** [comment] 2017-12-23 21:55
No, the problem is entirely on my side. when I mentioned that it worked on every file?
I forgot to delete the existing outputted image files. So it is a bug that just went through my tests.
I will be working on it.
But now I need to sleep. Sorry.
Also, there is plenty of exe files in this repository. Just try to delete the bmdview.exe, copy one of the other EXEs and rename the copy "bmdview.exe" It might help if the problem is in there.

**Comment by NoobisTF** [comment] 2017-12-23 22:12
Okay, please let me know when you have updated! Thanks!

**Comment by niacdoial** [comment] 2017-12-25 16:58
It should be fixed now.
Thanks for your patience!

**Comment by NoobisTF** [comment] 2017-12-25 17:15
:(
https://i.imgur.com/xYgHjPf.jpg

Doesn't crash on second time, and the textures are indeed in Textures/
But nothing imports and it reads that error.

**Comment by niacdoial** [comment] 2017-12-26 21:55
1: It should be fixed right now.
2: *Why am I this stupid?* This bug would have happened in every run, and I somehow derped my tests so much it worked each time.

**Comment by NoobisTF** [comment] 2017-12-27 00:28
Now I cannot even see Import BMD

**Comment by NoobisTF** [comment] 2017-12-27 00:31
Nevermind, my mistake.
Textures are in /Textures/, but no import.
This error prints when trying:
https://i.imgur.com/eNtV0oX.jpg
I think its the same as last time

**Comment by niacdoial** [comment] 2017-12-27 18:53
Okay.
Third time is the charm?

**Comment by NoobisTF** [comment] 2017-12-27 19:09
It is indeed!
Works for me! Thanks!

**Closed** 2018-02-14 15:42 UTC
